[tool.poetry]
name = "mMass"
version = "6.0.1"
description = "Mass Spectrometry Tool"
authors = ["Edd Salkield <edd@salkield.uk>", "Martin Strohalm"]
license = "GPL-3.0-or-later"
build = 'build.py'

packages = [
    { include = "gui" },
    { include = "mspy" },
    { include = "cx" },
    { include = "mmass.py" },
]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.0"
wxPython = "^4.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pyinstaller = "^4.0"
pywin32 = { version = "^228", platform = "win32" }

[tool.poetry.scripts]
mmass = "mmass:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

